"""Fixing articulo  model

Revision ID: 1fe53c2a7618
Revises: 8e3ebcc6e306
Create Date: 2025-07-31 11:22:25.109248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe53c2a7618'
down_revision: Union[str, Sequence[str], None] = '8e3ebcc6e306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
