"""Fixing articulo model

Revision ID: 44fb212c3c68
Revises: 1fe53c2a7618
Create Date: 2025-07-31 11:54:56.479447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44fb212c3c68'
down_revision: Union[str, Sequence[str], None] = '1fe53c2a7618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articulo', 'id_familia',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articulo', 'id_familia',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
