"""Añado descripcion a Color

Revision ID: 6bf07df23a15
Revises: cb5c12f91d1f
Create Date: 2025-07-30 14:00:26.786643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf07df23a15'
down_revision: Union[str, Sequence[str], None] = 'cb5c12f91d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color', sa.Column('descripcion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('color', 'descripcion')
    # ### end Alembic commands ###
