"""Descripción del cambio

Revision ID: 74693726dcb1
Revises: b0dc83e1269b
Create Date: 2025-07-30 13:12:14.505115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74693726dcb1'
down_revision: Union[str, Sequence[str], None] = 'b0dc83e1269b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articulo', sa.Column('codigo', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('articulo_sku_key'), 'articulo', type_='unique')
    op.create_unique_constraint(None, 'articulo', ['codigo'])
    op.drop_column('articulo', 'sku')
    op.add_column('producto_compuesto', sa.Column('id_familia', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'producto_compuesto', 'familia', ['id_familia'], ['id'])
    op.add_column('producto_simple', sa.Column('id_familia', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'producto_simple', 'familia', ['id_familia'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'producto_simple', type_='foreignkey')
    op.drop_column('producto_simple', 'id_familia')
    op.drop_constraint(None, 'producto_compuesto', type_='foreignkey')
    op.drop_column('producto_compuesto', 'id_familia')
    op.add_column('articulo', sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articulo', type_='unique')
    op.create_unique_constraint(op.f('articulo_sku_key'), 'articulo', ['sku'], postgresql_nulls_not_distinct=False)
    op.drop_column('articulo', 'codigo')
    # ### end Alembic commands ###
