"""Cambios recientes en modelos

Revision ID: a19b1b212aec
Revises: b0dc83e1269b
Create Date: 2025-07-28 13:37:56.201592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a19b1b212aec'
down_revision: Union[str, Sequence[str], None] = 'b0dc83e1269b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articulo', sa.Column('codigo', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('articulo_sku_key'), 'articulo', type_='unique')
    op.create_unique_constraint(None, 'articulo', ['codigo'])
    op.drop_column('articulo', 'sku')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articulo', sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articulo', type_='unique')
    op.create_unique_constraint(op.f('articulo_sku_key'), 'articulo', ['sku'], postgresql_nulls_not_distinct=False)
    op.drop_column('articulo', 'codigo')
    # ### end Alembic commands ###
