"""Primera migración: tablas iniciales

Revision ID: b0dc83e1269b
Revises: 
Create Date: 2025-07-28 11:40:35.109559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0dc83e1269b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('familia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_familia_id'), 'familia', ['id'], unique=False)
    op.create_table('precio_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin > fecha_inicio', name='check_fechas_compra_logicas'),
    sa.CheckConstraint('valor > 0', name='check_precio_compra_positivo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_precio_compra_id'), 'precio_compra', ['id'], unique=False)
    op.create_table('precio_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin > fecha_inicio', name='check_fechas_venta_logicas'),
    sa.CheckConstraint('valor > 0', name='check_precio_venta_positivo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_precio_venta_id'), 'precio_venta', ['id'], unique=False)
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nif_cif', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nif_cif')
    )
    op.create_index(op.f('ix_proveedor_id'), 'proveedor', ['id'], unique=False)
    op.create_table('articulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('id_familia', sa.Integer(), nullable=False),
    sa.Column('id_precio_venta', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_familia'], ['familia.id'], ),
    sa.ForeignKeyConstraint(['id_precio_venta'], ['precio_venta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_articulo_id'), 'articulo', ['id'], unique=False)
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('codigo_hex', sa.String(length=7), nullable=True),
    sa.Column('url_imagen', sa.String(length=2000), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('id_familia', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_familia'], ['familia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_color_id'), 'color', ['id'], unique=False)
    op.create_table('componente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('especificaciones', sa.Text(), nullable=True),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('id_precio_compra', sa.Integer(), nullable=True),
    sa.Column('id_color', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_color'], ['color.id'], ),
    sa.ForeignKeyConstraint(['id_precio_compra'], ['precio_compra.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_componente_id'), 'componente', ['id'], unique=False)
    op.create_table('pack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id_articulo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_articulo'], ['articulo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_articulo')
    )
    op.create_index(op.f('ix_pack_id'), 'pack', ['id'], unique=False)
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_producto', sa.String(length=20), nullable=False),
    sa.Column('id_articulo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("tipo_producto IN ('simple', 'compuesto')", name='check_tipo_producto'),
    sa.ForeignKeyConstraint(['id_articulo'], ['articulo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_articulo')
    )
    op.create_index(op.f('ix_producto_id'), 'producto', ['id'], unique=False)
    op.create_table('pack_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad_incluida', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_pack', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('cantidad_incluida > 0', name='check_cantidad_incluida_positiva'),
    sa.ForeignKeyConstraint(['id_pack'], ['pack.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_pack', 'id_producto', name='uk_pack_producto')
    )
    op.create_index(op.f('ix_pack_producto_id'), 'pack_producto', ['id'], unique=False)
    op.create_table('producto_compuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_producto')
    )
    op.create_index(op.f('ix_producto_compuesto_id'), 'producto_compuesto', ['id'], unique=False)
    op.create_table('producto_simple',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especificaciones', sa.Text(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('id_precio_compra', sa.Integer(), nullable=True),
    sa.Column('id_color', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_color'], ['color.id'], ),
    sa.ForeignKeyConstraint(['id_precio_compra'], ['precio_compra.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_producto')
    )
    op.create_index(op.f('ix_producto_simple_id'), 'producto_simple', ['id'], unique=False)
    op.create_table('componente_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad_necesaria', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_componente', sa.Integer(), nullable=False),
    sa.Column('id_producto_compuesto', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('cantidad_necesaria > 0', name='check_cantidad_necesaria_positiva'),
    sa.ForeignKeyConstraint(['id_componente'], ['componente.id'], ),
    sa.ForeignKeyConstraint(['id_producto_compuesto'], ['producto_compuesto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_componente', 'id_producto_compuesto', name='uk_componente_producto')
    )
    op.create_index(op.f('ix_componente_producto_id'), 'componente_producto', ['id'], unique=False)
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad_actual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad_minima', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cantidad_maxima', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ubicacion_almacen', sa.String(length=255), nullable=True),
    sa.Column('id_producto_simple', sa.Integer(), nullable=True),
    sa.Column('id_componente', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('cantidad_actual >= 0', name='check_cantidad_actual_positiva'),
    sa.CheckConstraint('cantidad_maxima IS NULL OR cantidad_maxima >= 0', name='check_cantidad_maxima_positiva'),
    sa.CheckConstraint('cantidad_maxima IS NULL OR cantidad_maxima >= cantidad_minima', name='check_stock_range'),
    sa.CheckConstraint('cantidad_minima >= 0', name='check_cantidad_minima_positiva'),
    sa.CheckConstraint('id_producto_simple IS NOT NULL AND id_componente IS NULL OR id_producto_simple IS NULL AND id_componente IS NOT NULL', name='check_stock_exclusive_relation'),
    sa.ForeignKeyConstraint(['id_componente'], ['componente.id'], ),
    sa.ForeignKeyConstraint(['id_producto_simple'], ['producto_simple.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_componente'),
    sa.UniqueConstraint('id_producto_simple')
    )
    op.create_index(op.f('ix_stock_id'), 'stock', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_id'), table_name='stock')
    op.drop_table('stock')
    op.drop_index(op.f('ix_componente_producto_id'), table_name='componente_producto')
    op.drop_table('componente_producto')
    op.drop_index(op.f('ix_producto_simple_id'), table_name='producto_simple')
    op.drop_table('producto_simple')
    op.drop_index(op.f('ix_producto_compuesto_id'), table_name='producto_compuesto')
    op.drop_table('producto_compuesto')
    op.drop_index(op.f('ix_pack_producto_id'), table_name='pack_producto')
    op.drop_table('pack_producto')
    op.drop_index(op.f('ix_producto_id'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_pack_id'), table_name='pack')
    op.drop_table('pack')
    op.drop_index(op.f('ix_componente_id'), table_name='componente')
    op.drop_table('componente')
    op.drop_index(op.f('ix_color_id'), table_name='color')
    op.drop_table('color')
    op.drop_index(op.f('ix_articulo_id'), table_name='articulo')
    op.drop_table('articulo')
    op.drop_index(op.f('ix_proveedor_id'), table_name='proveedor')
    op.drop_table('proveedor')
    op.drop_index(op.f('ix_precio_venta_id'), table_name='precio_venta')
    op.drop_table('precio_venta')
    op.drop_index(op.f('ix_precio_compra_id'), table_name='precio_compra')
    op.drop_table('precio_compra')
    op.drop_index(op.f('ix_familia_id'), table_name='familia')
    op.drop_table('familia')
    # ### end Alembic commands ###
